name = "download-helium"
main = "src/entry.py"
compatibility_date = "2026-08-01"
compatibility_flags = ["python_workers"]

routes = [
  { pattern = "download-helium.cuddles.rs", custom_domain = true }
]

[assets]
directory = "./public"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true